package org.pensionplan.pensionplan;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by owner on 2/24/2017.
 */

public class User extends RealmObject {
    public String          name;
    public String             email;
    public int             age;


    @PrimaryKey
    public String          id;

    @Ignore
    public int             sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name; }

    public void   setName(String name) {
        this.name = name; }

    public String    getAge() { return email; }

    public void   setAge(int age) {
        this.age = age; }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int    getSessionId() {
        return sessionId; }

    public void   setSessionId(int sessionId) {
        this.sessionId = sessionId; }
}


